version: 2.1

jobs:
  check new versions:
    machine: true
    resource_class: large
    steps:
      - checkout
      - run: ./tests/newversioncheck.sh
  emerge all ebuilds:
    machine: true
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: portage-pkgdir-emerge
      - run: ./tests/emerge-all-ebuilds.sh
      - save_cache:
          key: portage-pkgdir-emerge-{{ epoch }}
          paths:
            - ~/.portage-pkgdir
  emerge all live ebuilds:
    machine: true
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: portage-pkgdir-emerge
      - run: ./tests/emerge-all-live-ebuilds.sh
      - save_cache:
          key: portage-pkgdir-emerge-{{ epoch }}
          paths:
            - ~/.portage-pkgdir
  pkgcheck:
    machine: true
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: portage-pkgdir-pkgcheck
      - run: ./tests/pkgcheck.sh

      - save_cache:
          key: portage-pkgdir-pkgcheck-{{ epoch }}
          paths:
            - ~/.portage-pkgdir
  pkgcheck commits:
    machine: true
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: portage-pkgdir-pkgcheck
      - run: |
          git fetch
          ./tests/pkgcheck.sh --commits origin/master..HEAD

      - save_cache:
          key: portage-pkgdir-pkgcheck-{{ epoch }}
          paths:
            - ~/.portage-pkgdir
  emerge new or changed ebuilds:
    machine: true
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: portage-pkgdir-emerge
      - run: ./tests/emerge-new-or-changed-ebuilds.sh
      - save_cache:
          key: portage-pkgdir-emerge-{{ epoch }}
          paths:
            - ~/.portage-pkgdir
  generate site:
    machine: true
    steps:
      - checkout
      - run: ./docs/generate-site.sh
      - persist_to_workspace:
          root: docs/site
          paths:
            - index.md
  deploy site:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/docs
      - run: .circleci/deploy-gh-pages.sh


workflows:
  version: 2
  daily tests:
    triggers:
     - schedule:
         cron: "0 16 * * *"
         filters:
           branches:
             only:
               - master
    jobs:
      - check new versions
      - pkgcheck
      - emerge all ebuilds:
          requires:
            - pkgcheck
      - emerge all live ebuilds:
          requires:
            - emerge all ebuilds
  pullrequest:
    jobs:
      - pkgcheck commits:
          filters:
            branches:
              ignore: master
      - emerge new or changed ebuilds:
          requires:
            - pkgcheck commits
          filters:
            branches:
              ignore: master
  update site:
    jobs:
      - generate site:
          filters:
            branches:
              only:
                - master
      - deploy site:
          requires:
            - generate site
          filters:
            branches:
              only:
                - master
